# Barber Time: Configuración de Análisis y Linter
# Versión: 1.0.0 - Julio 2025
#
# Este archivo configura las reglas de análisis estático y linting para todo el proyecto.
# Estas reglas aseguran la consistencia, calidad y mantenibilidad del código.

# Incluye las reglas recomendadas de Flutter como base
include: package:flutter_lints/flutter.yaml

# Configuración del analizador
analyzer:
  errors:
    # Trata los TODOs como informacion, no como advertencias
    todo: info
  exclude:
    # Excluye archivos generados
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Reglas de documentación
    package_api_docs: true
    public_member_api_docs: true
    slash_for_doc_comments: true
    dangling_library_doc_comments: false
    
    # Estilo y formato
    prefer_single_quotes: true
    prefer_relative_imports: true
    always_use_package_imports: false
    directives_ordering: true
    sort_pub_dependencies: true
    lines_longer_than_80_chars: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_library_name: true

    # Buenas prácticas
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_future: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    cascade_invocations: true
    exhaustive_cases: true
    sized_box_for_whitespace: true
    unnecessary_await_in_return: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    use_super_parameters: true

    # Rendimiento
    avoid_function_literals_in_foreach_calls: true
    prefer_contains: true
    avoid_unnecessary_containers: true

# Configuración adicional del analizador
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 6
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - avoid-unused-parameters
    - no-equal-then-else
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-boolean-literal-compare

# Más información sobre las reglas del linter: https://dart.dev/tools/linter-rules
